# Generated by Django 3.2 on 2022-11-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='child_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='parent_user',
            new_name='user',
        ),
    ]
