# Generated by Django 4.1.3 on 2022-11-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_rename_chid_answer_child_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child_answer',
            old_name='created_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='parent_question',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
